name: Pull Request CI

on:
  pull_request:
    branches:
      - 'dev'
  merge_group:

jobs:
  check_changelog:
    name: "Check changelog"
    uses: ./.github/workflows/call-check-changelog.yml
  validate_gradle_wrapper:
    name: "Validate gradle wrapper"
    uses: ./.github/workflows/call-gradle-wrapper-validation.yml
  test:
    needs: validate_gradle_wrapper
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit test
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6 # v3
        with:
          arguments: testDebug
  detekt:
    needs: validate_gradle_wrapper
    name: "Check project by detekt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: detekt
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6 # v3
        with:
          arguments: detekt
  android_lint:
    needs: validate_gradle_wrapper
    name: "Check project by android`s lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Android lint
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6 # v3
        with:
          arguments: lint